/*
 Navicat Premium Data Transfer

 Source Server         : localhost
 Source Server Type    : MySQL
 Source Server Version : 80032
 Source Host           : localhost:3306
 Source Schema         : car

 Target Server Type    : MySQL
 Target Server Version : 80032
 File Encoding         : 65001

 Date: 16/07/2023 13:32:24
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for color_group
-- ----------------------------
DROP TABLE IF EXISTS `color_group`;
CREATE TABLE `color_group`  (
  `exteriorColor` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL,
  `interiorColor` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL,
  `count` int(0) NULL DEFAULT NULL
) ENGINE = InnoDB CHARACTER SET = utf8mb3 COLLATE = utf8mb3_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of color_group
-- ----------------------------
INSERT INTO `color_group` VALUES ('Abyss Blue Pearl', 'Black', 64);
INSERT INTO `color_group` VALUES ('Aegean Blue Metallic', 'Black', 73);
INSERT INTO `color_group` VALUES ('Agate Black Metallic', 'Black', 97);
INSERT INTO `color_group` VALUES ('Agate Black Metallic', 'Ebony', 86);
INSERT INTO `color_group` VALUES ('Alabaster Silver Metallic', 'Gray', 91);
INSERT INTO `color_group` VALUES ('Alloy Silver Metallic', 'Black', 168);
INSERT INTO `color_group` VALUES ('Alpine White', 'Beige', 50);
INSERT INTO `color_group` VALUES ('Alpine White', 'Black', 561);
INSERT INTO `color_group` VALUES ('Alpine White', 'Canberra Beige', 58);
INSERT INTO `color_group` VALUES ('Alpine White', 'Cognac', 65);
INSERT INTO `color_group` VALUES ('Apex Blue Pearl', 'Ebony', 57);
INSERT INTO `color_group` VALUES ('Arctic White', 'Black', 83);
INSERT INTO `color_group` VALUES ('Atomic Silver', 'Black', 212);
INSERT INTO `color_group` VALUES ('Atomic Silver', 'Red', 81);
INSERT INTO `color_group` VALUES ('Aurora Black Pearl', 'Black', 50);
INSERT INTO `color_group` VALUES ('Aurora Black', 'Black', 116);
INSERT INTO `color_group` VALUES ('Barcelona Red Metallic', 'Black', 58);
INSERT INTO `color_group` VALUES ('Billet Clearcoat Metallic', 'Black', 84);
INSERT INTO `color_group` VALUES ('Billet Clearcoat', 'Black', 132);
INSERT INTO `color_group` VALUES ('Billet Silver Metallic Clearcoat', 'Black', 988);
INSERT INTO `color_group` VALUES ('Billet Silver Metallic Clearcoat', 'Diesel Gray / Black', 54);
INSERT INTO `color_group` VALUES ('Black Cherry', 'Black', 67);
INSERT INTO `color_group` VALUES ('Black Clearcoat', 'Black', 703);
INSERT INTO `color_group` VALUES ('Black Clearcoat', 'Dark Slate Gray', 60);
INSERT INTO `color_group` VALUES ('Black Diamond', 'Black', 53);
INSERT INTO `color_group` VALUES ('Black Noir Pearl', 'Black', 112);
INSERT INTO `color_group` VALUES ('Black Noir Pearl', 'Gray', 69);
INSERT INTO `color_group` VALUES ('Black Obsidian', 'Graphite', 520);
INSERT INTO `color_group` VALUES ('Black Onyx', 'Black', 51);
INSERT INTO `color_group` VALUES ('Black Raven', 'Black', 94);
INSERT INTO `color_group` VALUES ('Black Raven', 'Jet Black', 386);
INSERT INTO `color_group` VALUES ('Black Sapphire Metallic', 'Black', 583);
INSERT INTO `color_group` VALUES ('Black', 'Beige', 214);
INSERT INTO `color_group` VALUES ('Black', 'Black', 5476);
INSERT INTO `color_group` VALUES ('Black', 'Brown', 135);
INSERT INTO `color_group` VALUES ('Black', 'Charcoal', 357);
INSERT INTO `color_group` VALUES ('Black', 'Charcoal Black', 62);
INSERT INTO `color_group` VALUES ('Black', 'Ebony', 519);
INSERT INTO `color_group` VALUES ('Black', 'Graphite', 122);
INSERT INTO `color_group` VALUES ('Black', 'Gray', 612);
INSERT INTO `color_group` VALUES ('Black', 'Jet Black', 922);
INSERT INTO `color_group` VALUES ('Black', 'Red', 100);
INSERT INTO `color_group` VALUES ('Black', 'Sport', 52);
INSERT INTO `color_group` VALUES ('Black', 'Tan', 225);
INSERT INTO `color_group` VALUES ('Black', 'Titan Black', 119);
INSERT INTO `color_group` VALUES ('Blizzard Pearl', 'Black', 112);
INSERT INTO `color_group` VALUES ('Blue Reflex Mica', 'Black', 52);
INSERT INTO `color_group` VALUES ('Blue', 'Beige', 134);
INSERT INTO `color_group` VALUES ('Blue', 'Black', 1102);
INSERT INTO `color_group` VALUES ('Blue', 'Ebony', 90);
INSERT INTO `color_group` VALUES ('Blue', 'Gray', 396);
INSERT INTO `color_group` VALUES ('Blue', 'Tan', 96);
INSERT INTO `color_group` VALUES ('Bright Silver Clearcoat Metallic', 'Black', 137);
INSERT INTO `color_group` VALUES ('Bright Silver Clearcoat Metallic', 'Diesel Gray / Black', 64);
INSERT INTO `color_group` VALUES ('Bright Silver Metallic', 'Charcoal', 52);
INSERT INTO `color_group` VALUES ('Bright Silver', 'Black', 84);
INSERT INTO `color_group` VALUES ('Bright White Clearcoat', 'Black', 2647);
INSERT INTO `color_group` VALUES ('Bright White Clearcoat', 'Diesel Gray / Black', 386);
INSERT INTO `color_group` VALUES ('Bright White Clearcoat', 'Diesel Gray/Black', 83);
INSERT INTO `color_group` VALUES ('Bright White Clearcoat', 'Global Black', 139);
INSERT INTO `color_group` VALUES ('Bright White Clearcoat', 'Gray', 84);
INSERT INTO `color_group` VALUES ('Bright White Clearcoat', 'Light Frost', 53);
INSERT INTO `color_group` VALUES ('Bright White', 'Black', 245);
INSERT INTO `color_group` VALUES ('Brilliant Black Crystal Pearlcoat', 'Black', 781);
INSERT INTO `color_group` VALUES ('Brilliant Black Crystal Pearlcoat', 'Diesel Gray / Black', 68);
INSERT INTO `color_group` VALUES ('Brilliant Black', 'Black', 287);
INSERT INTO `color_group` VALUES ('Brilliant Silver Metallic', 'Black', 55);
INSERT INTO `color_group` VALUES ('Brilliant Silver Metallic', 'Charcoal', 255);
INSERT INTO `color_group` VALUES ('Brilliant Silver', 'Black', 103);
INSERT INTO `color_group` VALUES ('Brilliant Silver', 'Charcoal', 259);
INSERT INTO `color_group` VALUES ('Brown', 'Black', 109);
INSERT INTO `color_group` VALUES ('Brown', 'Tan', 51);
INSERT INTO `color_group` VALUES ('Burgundy', 'Black', 147);
INSERT INTO `color_group` VALUES ('Cajun Red Tintcoat', 'Jet Black', 80);
INSERT INTO `color_group` VALUES ('Calypso Red', 'Black', 98);
INSERT INTO `color_group` VALUES ('Carbide Gray Metallic', 'Black', 76);
INSERT INTO `color_group` VALUES ('Carbon Black Metallic', 'Black', 113);
INSERT INTO `color_group` VALUES ('Carbon Black Metallic', 'Ebony', 63);
INSERT INTO `color_group` VALUES ('Carpathian Grey', 'Ebony', 95);
INSERT INTO `color_group` VALUES ('Carrara White Metallic', 'Black', 83);
INSERT INTO `color_group` VALUES ('Carrara White', 'Black', 55);
INSERT INTO `color_group` VALUES ('Caspian Blue', 'Charcoal', 50);
INSERT INTO `color_group` VALUES ('Caviar', 'Black', 159);
INSERT INTO `color_group` VALUES ('Cayenne Red', 'Charcoal', 63);
INSERT INTO `color_group` VALUES ('Celestial Silver Metallic', 'Black', 92);
INSERT INTO `color_group` VALUES ('Ceramic Gray Clearcoat', 'Black', 181);
INSERT INTO `color_group` VALUES ('Ceramic White', 'Black', 119);
INSERT INTO `color_group` VALUES ('Charcoal', 'Black', 87);
INSERT INTO `color_group` VALUES ('Chronos Gray Metallic', 'Black', 79);
INSERT INTO `color_group` VALUES ('Cinnabar Metallic', 'Ebony', 166);
INSERT INTO `color_group` VALUES ('Classic Silver Metallic', 'Black', 87);
INSERT INTO `color_group` VALUES ('Clear White', 'Black', 180);
INSERT INTO `color_group` VALUES ('Corris Grey', 'Ebony', 85);
INSERT INTO `color_group` VALUES ('Crimson Red Pearl', 'Black', 67);
INSERT INTO `color_group` VALUES ('Crystal Black Pearl', 'Black', 632);
INSERT INTO `color_group` VALUES ('Crystal Black Pearl', 'Ebony', 80);
INSERT INTO `color_group` VALUES ('Crystal Black Pearl', 'Gray', 106);
INSERT INTO `color_group` VALUES ('Crystal Black Silica', 'Black', 427);
INSERT INTO `color_group` VALUES ('Crystal Black Silica', 'Gray', 119);
INSERT INTO `color_group` VALUES ('Crystal Black Silica', 'Ivory', 108);
INSERT INTO `color_group` VALUES ('Crystal White Metallic', 'Blond', 68);
INSERT INTO `color_group` VALUES ('Crystal White Metallic', 'Charcoal', 99);
INSERT INTO `color_group` VALUES ('Crystal White Pearl', 'Black', 532);
INSERT INTO `color_group` VALUES ('Crystal White Pearl', 'Gray', 282);
INSERT INTO `color_group` VALUES ('Crystal White Pearl', 'Ivory', 77);
INSERT INTO `color_group` VALUES ('Crystal White Pearl', 'Java Brown', 50);
INSERT INTO `color_group` VALUES ('Crystal White Tri-Coat', 'Black', 116);
INSERT INTO `color_group` VALUES ('Crystal White Tri-Coat', 'Cirrus', 56);
INSERT INTO `color_group` VALUES ('Crystal White Tri-Coat', 'Jet Black', 232);
INSERT INTO `color_group` VALUES ('Crystal White Tri-Coat', 'Shara Beige', 50);
INSERT INTO `color_group` VALUES ('Dark Graphite Metallic', 'Black', 122);
INSERT INTO `color_group` VALUES ('Dark Gray Metallic', 'Black', 154);
INSERT INTO `color_group` VALUES ('Dark Gray Metallic', 'Gray', 111);
INSERT INTO `color_group` VALUES ('Dark Moon Blue Metallic', 'Ebony', 76);
INSERT INTO `color_group` VALUES ('Dark Sky Metallic', 'Jet Black', 71);
INSERT INTO `color_group` VALUES ('Daytona Gray Pearl Effect', 'Black', 229);
INSERT INTO `color_group` VALUES ('Db Black Clearcoat', 'Black', 113);
INSERT INTO `color_group` VALUES ('Db Black Crystal Clearcoat', 'Black', 157);
INSERT INTO `color_group` VALUES ('Deep Black Pearl Effect', 'Black', 186);
INSERT INTO `color_group` VALUES ('Deep Black Pearl Effect', 'Titan Black', 400);
INSERT INTO `color_group` VALUES ('Deep Blue Pearl', 'Charcoal', 54);
INSERT INTO `color_group` VALUES ('Deep Cherry Red Crystal Pearlcoat', 'Black', 101);
INSERT INTO `color_group` VALUES ('Deep Crystal Blue Mica', 'Black', 342);
INSERT INTO `color_group` VALUES ('Deep Sea Blue', 'Black', 50);
INSERT INTO `color_group` VALUES ('Delmonico Red Pearlcoat', 'Black', 232);
INSERT INTO `color_group` VALUES ('Delmonico Red Pearlcoat', 'Diesel Gray / Black', 54);
INSERT INTO `color_group` VALUES ('Denim Blue Metallic', 'Blond', 62);
INSERT INTO `color_group` VALUES ('Denim Blue Metallic', 'Charcoal', 54);
INSERT INTO `color_group` VALUES ('Destroyer Gray Clearcoat', 'Black', 162);
INSERT INTO `color_group` VALUES ('Diamond Black Crystal Pearlcoat', 'Black', 92);
INSERT INTO `color_group` VALUES ('Diamond Black', 'Black', 852);
INSERT INTO `color_group` VALUES ('Diamond Black', 'Diesel Gray / Black', 63);
INSERT INTO `color_group` VALUES ('Diamond Black', 'Global Black', 136);
INSERT INTO `color_group` VALUES ('Diamond Red', 'Black', 91);
INSERT INTO `color_group` VALUES ('Ebony Black', 'Black', 255);
INSERT INTO `color_group` VALUES ('Ebony Black', 'Satin Black', 51);
INSERT INTO `color_group` VALUES ('Ebony Twilight Metallic', 'Dark Galvanized', 82);
INSERT INTO `color_group` VALUES ('Ebony Twilight Metallic', 'Ebony', 496);
INSERT INTO `color_group` VALUES ('Ebony Twilight Metallic', 'Jet Black', 337);
INSERT INTO `color_group` VALUES ('Eiger Grey', 'Ebony', 104);
INSERT INTO `color_group` VALUES ('Eminent White Pearl', 'Black', 173);
INSERT INTO `color_group` VALUES ('Eminent White Pearl', 'Parchment', 78);
INSERT INTO `color_group` VALUES ('Eternal Blue Mica', 'Black', 116);
INSERT INTO `color_group` VALUES ('Everlasting Silver', 'Black', 115);
INSERT INTO `color_group` VALUES ('F8 Green', 'Black', 142);
INSERT INTO `color_group` VALUES ('Fathom Blue Pearlcoat', 'Black', 86);
INSERT INTO `color_group` VALUES ('Firecracker Red Clearcoat', 'Black', 151);
INSERT INTO `color_group` VALUES ('Firenze Red', 'Ebony', 84);
INSERT INTO `color_group` VALUES ('Flame Red Clearcoat', 'Black', 149);
INSERT INTO `color_group` VALUES ('Flame Red Clearcoat', 'Diesel Gray / Black', 53);
INSERT INTO `color_group` VALUES ('Florett Silver Metallic', 'Black', 313);
INSERT INTO `color_group` VALUES ('Fresh Powder', 'Charcoal', 50);
INSERT INTO `color_group` VALUES ('Frost White Pearl', 'Gray', 63);
INSERT INTO `color_group` VALUES ('Frostbite', 'Black', 146);
INSERT INTO `color_group` VALUES ('Fuji White', 'Ebony', 430);
INSERT INTO `color_group` VALUES ('Fuji White', 'Ebony / Ebony', 135);
INSERT INTO `color_group` VALUES ('Fuji White', 'Light Oyster', 59);
INSERT INTO `color_group` VALUES ('Glacial White Pearl', 'Black', 142);
INSERT INTO `color_group` VALUES ('Glacier Silver Metallic', 'Black', 198);
INSERT INTO `color_group` VALUES ('Glacier White Metallic', 'Black', 429);
INSERT INTO `color_group` VALUES ('Glacier White', 'Black', 68);
INSERT INTO `color_group` VALUES ('Glacier White', 'Charcoal', 151);
INSERT INTO `color_group` VALUES ('Glacier White', 'Gray', 86);
INSERT INTO `color_group` VALUES ('Gloss Black', 'Black', 170);
INSERT INTO `color_group` VALUES ('Go Mango!', 'Black', 125);
INSERT INTO `color_group` VALUES ('Granite Clearcoat Metallic', 'Black', 65);
INSERT INTO `color_group` VALUES ('Granite Clearcoat', 'Black', 52);
INSERT INTO `color_group` VALUES ('Granite Crystal Clearcoat Metallic', 'Black', 1583);
INSERT INTO `color_group` VALUES ('Granite Crystal Clearcoat Metallic', 'Diesel Gray / Black', 126);
INSERT INTO `color_group` VALUES ('Granite Crystal Metallic Clearcoat', 'Black', 134);
INSERT INTO `color_group` VALUES ('Granite Pearlcoat', 'Black', 195);
INSERT INTO `color_group` VALUES ('Graphite Gray Metallic', 'Black', 76);
INSERT INTO `color_group` VALUES ('Graphite Metallic', 'Jet Black', 62);
INSERT INTO `color_group` VALUES ('Graphite Shadow', 'Graphite', 462);
INSERT INTO `color_group` VALUES ('Gravity Gray', 'Black', 199);
INSERT INTO `color_group` VALUES ('Gray Metallic', 'Black', 141);
INSERT INTO `color_group` VALUES ('Gray', 'Beige', 105);
INSERT INTO `color_group` VALUES ('Gray', 'Black', 2702);
INSERT INTO `color_group` VALUES ('Gray', 'Charcoal', 95);
INSERT INTO `color_group` VALUES ('Gray', 'Ebony', 198);
INSERT INTO `color_group` VALUES ('Gray', 'Graphite', 59);
INSERT INTO `color_group` VALUES ('Gray', 'Gray', 811);
INSERT INTO `color_group` VALUES ('Gray', 'Jet Black', 134);
INSERT INTO `color_group` VALUES ('Gray', 'Red', 59);
INSERT INTO `color_group` VALUES ('Gray', 'Tan', 97);
INSERT INTO `color_group` VALUES ('Green', 'Black', 144);
INSERT INTO `color_group` VALUES ('Gun Metallic', 'Black', 259);
INSERT INTO `color_group` VALUES ('Gun Metallic', 'Charcoal', 616);
INSERT INTO `color_group` VALUES ('Gun Metallic', 'Graphite', 95);
INSERT INTO `color_group` VALUES ('Hakuba Silver', 'Ebony', 52);
INSERT INTO `color_group` VALUES ('Hampton Gray', 'Black', 70);
INSERT INTO `color_group` VALUES ('Hermosa Blue', 'Graphite', 203);
INSERT INTO `color_group` VALUES ('Hermosa Blue', 'Wheat', 89);
INSERT INTO `color_group` VALUES ('Hydro Blue Pearlcoat', 'Black', 96);
INSERT INTO `color_group` VALUES ('Hyper White', 'Black', 55);
INSERT INTO `color_group` VALUES ('Ibis White', 'Black', 257);
INSERT INTO `color_group` VALUES ('Ice Silver Metallic', 'Black', 800);
INSERT INTO `color_group` VALUES ('Ice Silver Metallic', 'Gray', 141);
INSERT INTO `color_group` VALUES ('Iconic Silver Metallic', 'Ebony', 73);
INSERT INTO `color_group` VALUES ('Indigo Blue', 'Black', 80);
INSERT INTO `color_group` VALUES ('Indus Silver', 'Ebony', 67);
INSERT INTO `color_group` VALUES ('Inferno Red', 'Black', 50);
INSERT INTO `color_group` VALUES ('Infinite Black Metallic', 'Ebony', 192);
INSERT INTO `color_group` VALUES ('Ingot Silver Metallic', 'Black', 71);
INSERT INTO `color_group` VALUES ('Ingot Silver Metallic', 'Charcoal Black', 63);
INSERT INTO `color_group` VALUES ('Ingot Silver Metallic', 'Ebony', 66);
INSERT INTO `color_group` VALUES ('Ingot Silver', 'Ebony', 58);
INSERT INTO `color_group` VALUES ('Intense Blue', 'Black', 67);
INSERT INTO `color_group` VALUES ('Iridescent Pearl Tricoat', 'Jet Black', 126);
INSERT INTO `color_group` VALUES ('Iridium Metallic', 'Jet Black', 94);
INSERT INTO `color_group` VALUES ('Iridium Silver Metallic', 'Black', 157);
INSERT INTO `color_group` VALUES ('Jasmine Green Metallic', 'Gray', 50);
INSERT INTO `color_group` VALUES ('Jazz Blue Pearlcoat', 'Black', 52);
INSERT INTO `color_group` VALUES ('Jet Black Metallic', 'Black', 84);
INSERT INTO `color_group` VALUES ('Jet Black Mica', 'Black', 731);
INSERT INTO `color_group` VALUES ('Jet Black', 'Black', 397);
INSERT INTO `color_group` VALUES ('Labrador Black Metallic', 'Black', 62);
INSERT INTO `color_group` VALUES ('Labrador Black Pearl', 'Black', 93);
INSERT INTO `color_group` VALUES ('Lakeside Blue', 'Gray', 96);
INSERT INTO `color_group` VALUES ('Liquid Carbon Metallic', 'Ebony', 75);
INSERT INTO `color_group` VALUES ('Liquid Platinum', 'Graphite', 230);
INSERT INTO `color_group` VALUES ('Liquid Silver Metallic', 'Black', 83);
INSERT INTO `color_group` VALUES ('Lunar Silver Metallic', 'Black', 255);
INSERT INTO `color_group` VALUES ('Lunar Silver Metallic', 'Ebony', 129);
INSERT INTO `color_group` VALUES ('Lunar Silver Metallic', 'Gray', 171);
INSERT INTO `color_group` VALUES ('Machine Gray Metallic', 'Black', 448);
INSERT INTO `color_group` VALUES ('Machine Gray', 'Gray', 52);
INSERT INTO `color_group` VALUES ('Magnetic Black', 'Black', 81);
INSERT INTO `color_group` VALUES ('Magnetic Black', 'Charcoal', 192);
INSERT INTO `color_group` VALUES ('Magnetic Gray Metallic', 'Black', 230);
INSERT INTO `color_group` VALUES ('Magnetic Gray Metallic', 'Graphite', 60);
INSERT INTO `color_group` VALUES ('Magnetic Metallic', 'Ebony', 96);
INSERT INTO `color_group` VALUES ('Magnetite Gray Metallic', 'Black', 351);
INSERT INTO `color_group` VALUES ('Magnetite Gray Metallic', 'Gray', 131);
INSERT INTO `color_group` VALUES ('Majestic Black Pearl', 'Ebony', 240);
INSERT INTO `color_group` VALUES ('Majestic Black Pearl', 'Red', 62);
INSERT INTO `color_group` VALUES ('Majestic White', 'Graphite', 295);
INSERT INTO `color_group` VALUES ('Majestic White', 'Wheat', 109);
INSERT INTO `color_group` VALUES ('Manhattan Gray Metallic', 'Black', 143);
INSERT INTO `color_group` VALUES ('Maroon', 'Black', 72);
INSERT INTO `color_group` VALUES ('Matador Red Mica', 'Black', 56);
INSERT INTO `color_group` VALUES ('Maximum Steel Metallic', 'Black', 216);
INSERT INTO `color_group` VALUES ('Mercury Gray Metallic', 'Black', 138);
INSERT INTO `color_group` VALUES ('Metallic', 'Black', 85);
INSERT INTO `color_group` VALUES ('Metallic', 'Global Black', 62);
INSERT INTO `color_group` VALUES ('Meteor Gray Mica', 'Black', 87);
INSERT INTO `color_group` VALUES ('Midnight Black Metallic', 'Black', 244);
INSERT INTO `color_group` VALUES ('Midnight Black', 'Black', 131);
INSERT INTO `color_group` VALUES ('Midnight Blue Metallic', 'Jet Black', 59);
INSERT INTO `color_group` VALUES ('Mineral Black', 'Graphite', 64);
INSERT INTO `color_group` VALUES ('Mineral Gray Metallic', 'Black', 210);
INSERT INTO `color_group` VALUES ('Mineral Gray', 'Gray', 67);
INSERT INTO `color_group` VALUES ('Mineral White Metallic', 'Black', 142);
INSERT INTO `color_group` VALUES ('Mineral White Metallic', 'Cognac', 60);
INSERT INTO `color_group` VALUES ('Modern Steel Metallic', 'Black', 330);
INSERT INTO `color_group` VALUES ('Modern Steel Metallic', 'Ebony', 131);
INSERT INTO `color_group` VALUES ('Modern Steel Metallic', 'Gray', 246);
INSERT INTO `color_group` VALUES ('Molten Silver', 'Gray', 60);
INSERT INTO `color_group` VALUES ('Monsoon Gray Metallic', 'Black', 117);
INSERT INTO `color_group` VALUES ('Moonlight Blue Metallic', 'Black', 64);
INSERT INTO `color_group` VALUES ('Moonstone Gray Metallic', 'Ebony', 59);
INSERT INTO `color_group` VALUES ('Moonstone White', 'Graphite', 97);
INSERT INTO `color_group` VALUES ('Mosaic Black Metallic', 'Jet Black', 195);
INSERT INTO `color_group` VALUES ('Mythos Black Metallic', 'Black', 518);
INSERT INTO `color_group` VALUES ('Narvik Black', 'Ebony', 102);
INSERT INTO `color_group` VALUES ('Narvik Black', 'Ebony / Ebony', 89);
INSERT INTO `color_group` VALUES ('Navarra Blue Metallic', 'Black', 139);
INSERT INTO `color_group` VALUES ('Nebula Gray Pearl', 'Black', 200);
INSERT INTO `color_group` VALUES ('Night Blue Metallic', 'Black', 61);
INSERT INTO `color_group` VALUES ('Nightfall Gray Metallic', 'Jet Black', 76);
INSERT INTO `color_group` VALUES ('Obsidian Black Metallic', 'Black', 122);
INSERT INTO `color_group` VALUES ('Obsidian Black', 'Black', 161);
INSERT INTO `color_group` VALUES ('Obsidian Blue Pearl', 'Gray', 99);
INSERT INTO `color_group` VALUES ('Octane Red Pearlcoat', 'Black', 279);
INSERT INTO `color_group` VALUES ('Onyx Black Metallic', 'Charcoal', 175);
INSERT INTO `color_group` VALUES ('Onyx Black', 'Black', 122);
INSERT INTO `color_group` VALUES ('Onyx Black', 'Charcoal', 51);
INSERT INTO `color_group` VALUES ('Onyx Black', 'Jet Black', 792);
INSERT INTO `color_group` VALUES ('Orange', 'Black', 106);
INSERT INTO `color_group` VALUES ('Orca Black Metallic', 'Black', 100);
INSERT INTO `color_group` VALUES ('Osmium Gray Metallic', 'Charcoal', 66);
INSERT INTO `color_group` VALUES ('Oxford White', 'Black', 153);
INSERT INTO `color_group` VALUES ('Oxford White', 'Ebony', 147);
INSERT INTO `color_group` VALUES ('Oxford White', 'Gray', 59);
INSERT INTO `color_group` VALUES ('Oxford White', 'Medium Earth Gray', 162);
INSERT INTO `color_group` VALUES ('Pacific Blue Metallic', 'Jet Black', 81);
INSERT INTO `color_group` VALUES ('Pacific Blue', 'Black', 87);
INSERT INTO `color_group` VALUES ('Passion Red', 'Black', 55);
INSERT INTO `color_group` VALUES ('Patriot Blue Pearlcoat', 'Black', 106);
INSERT INTO `color_group` VALUES ('Pearl White', 'Black', 147);
INSERT INTO `color_group` VALUES ('Pearl White', 'Charcoal', 71);
INSERT INTO `color_group` VALUES ('Performance Red Pearl', 'Ebony', 56);
INSERT INTO `color_group` VALUES ('Phantom Black', 'Black', 136);
INSERT INTO `color_group` VALUES ('Phantom Black', 'Graphite', 61);
INSERT INTO `color_group` VALUES ('Phantom Black', 'Gray', 118);
INSERT INTO `color_group` VALUES ('Phytonic Blue Metallic', 'Black', 50);
INSERT INTO `color_group` VALUES ('Pitch Black Clearcoat', 'Black', 557);
INSERT INTO `color_group` VALUES ('Platinum Graphite', 'Black', 62);
INSERT INTO `color_group` VALUES ('Platinum Gray Metallic', 'Black', 236);
INSERT INTO `color_group` VALUES ('Platinum Gray Metallic', 'Titan Black', 450);
INSERT INTO `color_group` VALUES ('Platinum White Pearl', 'Black', 442);
INSERT INTO `color_group` VALUES ('Platinum White Pearl', 'Ebony', 196);
INSERT INTO `color_group` VALUES ('Platinum White Pearl', 'Gray', 65);
INSERT INTO `color_group` VALUES ('Platinum White Pearl', 'Parchment', 107);
INSERT INTO `color_group` VALUES ('Platinum White Pearl', 'Red', 85);
INSERT INTO `color_group` VALUES ('Polar White', 'Black', 315);
INSERT INTO `color_group` VALUES ('Polar White', 'Macchiato Beige', 67);
INSERT INTO `color_group` VALUES ('Polished Metal Metallic', 'Gray', 54);
INSERT INTO `color_group` VALUES ('Polymetal Gray Metallic', 'Black', 95);
INSERT INTO `color_group` VALUES ('Polymetal Gray Metallic', 'Red', 139);
INSERT INTO `color_group` VALUES ('Portofino Gray', 'Black', 116);
INSERT INTO `color_group` VALUES ('Predawn Gray Mica', 'Ash', 71);
INSERT INTO `color_group` VALUES ('Predawn Gray Mica', 'Black', 51);
INSERT INTO `color_group` VALUES ('Pristine White', 'Ebony', 99);
INSERT INTO `color_group` VALUES ('Pristine White', 'Sandstone', 113);
INSERT INTO `color_group` VALUES ('Pure White', 'Black', 231);
INSERT INTO `color_group` VALUES ('Pure White', 'Gray', 56);
INSERT INTO `color_group` VALUES ('Pure White', 'Titan Black', 511);
INSERT INTO `color_group` VALUES ('Pyrite Silver Metallic', 'Black', 110);
INSERT INTO `color_group` VALUES ('Pyrite Silver Metallic', 'Titan Black', 140);
INSERT INTO `color_group` VALUES ('Quartz Blue Pearl', 'Gray', 57);
INSERT INTO `color_group` VALUES ('Quartz White Pearl', 'Beige', 55);
INSERT INTO `color_group` VALUES ('Quartz White Pearl', 'Gray', 105);
INSERT INTO `color_group` VALUES ('Quartz White', 'Black', 109);
INSERT INTO `color_group` VALUES ('Quicksilver Metallic', 'Ebony', 331);
INSERT INTO `color_group` VALUES ('Quicksilver Metallic', 'Jet Black', 278);
INSERT INTO `color_group` VALUES ('Radiant Red', 'Jet Black', 53);
INSERT INTO `color_group` VALUES ('Radiant Silver Metallic', 'Black', 72);
INSERT INTO `color_group` VALUES ('Radiant Silver Metallic', 'Jet Black', 161);
INSERT INTO `color_group` VALUES ('Red Quartz Tintcoat', 'Jet Black', 102);
INSERT INTO `color_group` VALUES ('Red', 'Beige', 89);
INSERT INTO `color_group` VALUES ('Red', 'Black', 1134);
INSERT INTO `color_group` VALUES ('Red', 'Ebony', 69);
INSERT INTO `color_group` VALUES ('Red', 'Gray', 208);
INSERT INTO `color_group` VALUES ('Red', 'Jet Black', 140);
INSERT INTO `color_group` VALUES ('Red', 'Tan', 85);
INSERT INTO `color_group` VALUES ('Redline 2 Coat Pearl', 'Black', 108);
INSERT INTO `color_group` VALUES ('Reflex Silver Metallic', 'Titan Black', 137);
INSERT INTO `color_group` VALUES ('Rhino Clearcoat', 'Black', 61);
INSERT INTO `color_group` VALUES ('Ruby Flare Pearl', 'Black', 57);
INSERT INTO `color_group` VALUES ('Samurai Gray Metallic', 'Black', 74);
INSERT INTO `color_group` VALUES ('Santorini Black', 'Ebony', 522);
INSERT INTO `color_group` VALUES ('Santorini Black', 'Ebony / Ebony', 104);
INSERT INTO `color_group` VALUES ('Sapphire Blue', 'Black', 78);
INSERT INTO `color_group` VALUES ('Sarge Green Clearcoat', 'Black', 51);
INSERT INTO `color_group` VALUES ('Satin Steel Metallic', 'Black', 92);
INSERT INTO `color_group` VALUES ('Satin Steel Metallic', 'Dark Galvanized', 65);
INSERT INTO `color_group` VALUES ('Satin Steel Metallic', 'Ebony', 147);
INSERT INTO `color_group` VALUES ('Satin Steel Metallic', 'Jet Black', 397);
INSERT INTO `color_group` VALUES ('Scarlet Ember', 'Charcoal', 89);
INSERT INTO `color_group` VALUES ('Scarlet Red', 'Gray', 68);
INSERT INTO `color_group` VALUES ('Selenite Gray Metallic', 'Black', 68);
INSERT INTO `color_group` VALUES ('Shadow Black', 'Black', 129);
INSERT INTO `color_group` VALUES ('Shadow Black', 'Ebony', 158);
INSERT INTO `color_group` VALUES ('Shadow Gray Metallic', 'Jet Black', 84);
INSERT INTO `color_group` VALUES ('Shale Gray Metallic', 'Gray', 90);
INSERT INTO `color_group` VALUES ('Shimmering Silver', 'Black', 51);
INSERT INTO `color_group` VALUES ('Silk Blue Metallic', 'Titan Black', 68);
INSERT INTO `color_group` VALUES ('Silky Silver', 'Black', 97);
INSERT INTO `color_group` VALUES ('Silver Ice Metallic', 'Black', 123);
INSERT INTO `color_group` VALUES ('Silver Ice Metallic', 'Ebony', 64);
INSERT INTO `color_group` VALUES ('Silver Ice Metallic', 'Jet Black', 338);
INSERT INTO `color_group` VALUES ('Silver Lining Metallic', 'Black', 103);
INSERT INTO `color_group` VALUES ('Silver Metallic', 'Black', 54);
INSERT INTO `color_group` VALUES ('Silver Mist Clearcoat', 'Black', 150);
INSERT INTO `color_group` VALUES ('Silver Sky Metallic', 'Black', 70);
INSERT INTO `color_group` VALUES ('Silver Zynith', 'Global Black', 73);
INSERT INTO `color_group` VALUES ('Silver', 'Beige', 56);
INSERT INTO `color_group` VALUES ('Silver', 'Black', 1980);
INSERT INTO `color_group` VALUES ('Silver', 'Charcoal', 80);
INSERT INTO `color_group` VALUES ('Silver', 'Ebony', 118);
INSERT INTO `color_group` VALUES ('Silver', 'Gray', 604);
INSERT INTO `color_group` VALUES ('Sinamon Stick', 'Black', 51);
INSERT INTO `color_group` VALUES ('Slate Gray', 'Graphite', 58);
INSERT INTO `color_group` VALUES ('Smoke Show', 'Black', 72);
INSERT INTO `color_group` VALUES ('Snow White Pearl', 'Black', 386);
INSERT INTO `color_group` VALUES ('Snow White Pearl', 'Gray', 74);
INSERT INTO `color_group` VALUES ('Snow White Pearl', 'Satin Black', 51);
INSERT INTO `color_group` VALUES ('Snowflake White Pearl Mica', 'Black', 156);
INSERT INTO `color_group` VALUES ('Snowflake White Pearl', 'Black', 255);
INSERT INTO `color_group` VALUES ('Sonic Gray Pearl', 'Black', 134);
INSERT INTO `color_group` VALUES ('Sonic Silver Metallic', 'Black', 310);
INSERT INTO `color_group` VALUES ('Soul Red Crystal Metallic', 'Black', 325);
INSERT INTO `color_group` VALUES ('Soul Red Metallic', 'Black', 87);
INSERT INTO `color_group` VALUES ('Space Gray Metallic', 'Black', 67);
INSERT INTO `color_group` VALUES ('Sparkling Silver', 'Black', 142);
INSERT INTO `color_group` VALUES ('Sparkling Silver', 'Gray', 57);
INSERT INTO `color_group` VALUES ('Steel Gray', 'Black', 111);
INSERT INTO `color_group` VALUES ('Stellar Black Metallic', 'Black', 110);
INSERT INTO `color_group` VALUES ('Stellar Black Metallic', 'Jet Black', 248);
INSERT INTO `color_group` VALUES ('Still Night Pearl', 'Black', 66);
INSERT INTO `color_group` VALUES ('Sting Gray Clearcoat', 'Black', 155);
INSERT INTO `color_group` VALUES ('Stormy Sea', 'Black', 74);
INSERT INTO `color_group` VALUES ('Summit White', 'Black', 342);
INSERT INTO `color_group` VALUES ('Summit White', 'Cocoa / Dune', 93);
INSERT INTO `color_group` VALUES ('Summit White', 'Dark Ash', 84);
INSERT INTO `color_group` VALUES ('Summit White', 'Dark Galvanized', 75);
INSERT INTO `color_group` VALUES ('Summit White', 'Ebony', 545);
INSERT INTO `color_group` VALUES ('Summit White', 'Jet Black', 1524);
INSERT INTO `color_group` VALUES ('Summit White', 'Jet Black / Dark Ash', 86);
INSERT INTO `color_group` VALUES ('Summit White', 'Medium Pewter', 151);
INSERT INTO `color_group` VALUES ('Summit White', 'Whisper Beige', 52);
INSERT INTO `color_group` VALUES ('Super Black', 'Black', 113);
INSERT INTO `color_group` VALUES ('Super Black', 'Charcoal', 255);
INSERT INTO `color_group` VALUES ('Super White', 'Black', 197);
INSERT INTO `color_group` VALUES ('Super White', 'Graphite', 62);
INSERT INTO `color_group` VALUES ('Symphony Silver', 'Gray', 130);
INSERT INTO `color_group` VALUES ('Tan', 'Black', 50);
INSERT INTO `color_group` VALUES ('Thunder Gray', 'Black', 60);
INSERT INTO `color_group` VALUES ('Titanium Gray', 'Black', 69);
INSERT INTO `color_group` VALUES ('Titanium Rush Metallic', 'Jet Black', 54);
INSERT INTO `color_group` VALUES ('Tornado Red', 'Titan Black', 63);
INSERT INTO `color_group` VALUES ('Torred Clearcoat', 'Black', 140);
INSERT INTO `color_group` VALUES ('Tourmaline Blue Metallic', 'Titan Black', 102);
INSERT INTO `color_group` VALUES ('Triple Nickel Clearcoat', 'Black', 135);
INSERT INTO `color_group` VALUES ('True Blue Pearlcoat', 'Black', 81);
INSERT INTO `color_group` VALUES ('Tungsten Metallic', 'Ivory', 87);
INSERT INTO `color_group` VALUES ('Tungsten Metallic', 'Jet Black', 65);
INSERT INTO `color_group` VALUES ('Tuxedo Black Metallic', 'Black', 62);
INSERT INTO `color_group` VALUES ('Tuxedo Black Metallic', 'Charcoal Black', 51);
INSERT INTO `color_group` VALUES ('Twilight Black', 'Black', 67);
INSERT INTO `color_group` VALUES ('Twilight Black', 'Gray', 58);
INSERT INTO `color_group` VALUES ('Twilight Blue Metallic', 'Black', 52);
INSERT INTO `color_group` VALUES ('Ultra Black', 'Black', 85);
INSERT INTO `color_group` VALUES ('Ultra White', 'Black', 120);
INSERT INTO `color_group` VALUES ('Ultra White', 'Red', 95);
INSERT INTO `color_group` VALUES ('Velvet Red Pearlcoat', 'Black', 447);
INSERT INTO `color_group` VALUES ('Velvet Red Pearlcoat', 'Global Black', 54);
INSERT INTO `color_group` VALUES ('Venetian Red Pearl', 'Black', 82);
INSERT INTO `color_group` VALUES ('Vice White', 'Black', 73);
INSERT INTO `color_group` VALUES ('Volcano Grey Metallic', 'Black', 56);
INSERT INTO `color_group` VALUES ('White Clearcoat', 'Black', 52);
INSERT INTO `color_group` VALUES ('White Diamond Pearl', 'Beige', 72);
INSERT INTO `color_group` VALUES ('White Diamond Pearl', 'Black', 81);
INSERT INTO `color_group` VALUES ('White Diamond', 'Black', 101);
INSERT INTO `color_group` VALUES ('White Frost Tri-Coat', 'Ebony', 87);
INSERT INTO `color_group` VALUES ('White Frost Tri-Coat', 'Jet Black', 179);
INSERT INTO `color_group` VALUES ('White Frost Tri-Coat', 'Whisper Beige', 62);
INSERT INTO `color_group` VALUES ('White Knuckle Clearcoat', 'Black', 574);
INSERT INTO `color_group` VALUES ('White Platinum Tri-Coat Metallic', 'Ebony', 70);
INSERT INTO `color_group` VALUES ('White', 'Beige', 370);
INSERT INTO `color_group` VALUES ('White', 'Black', 3370);
INSERT INTO `color_group` VALUES ('White', 'Brown', 160);
INSERT INTO `color_group` VALUES ('White', 'Charcoal', 238);
INSERT INTO `color_group` VALUES ('White', 'Diesel Gray / Black', 78);
INSERT INTO `color_group` VALUES ('White', 'Ebony', 260);
INSERT INTO `color_group` VALUES ('White', 'Graphite', 134);
INSERT INTO `color_group` VALUES ('White', 'Gray', 924);
INSERT INTO `color_group` VALUES ('White', 'Ivory', 103);
INSERT INTO `color_group` VALUES ('White', 'Jet Black', 151);
INSERT INTO `color_group` VALUES ('White', 'Light Gray', 68);
INSERT INTO `color_group` VALUES ('White', 'Parchment', 84);
INSERT INTO `color_group` VALUES ('White', 'Red', 102);
INSERT INTO `color_group` VALUES ('White', 'Sandstone', 59);
INSERT INTO `color_group` VALUES ('White', 'Tan', 432);
INSERT INTO `color_group` VALUES ('Wind Chill Pearl', 'Black', 55);
INSERT INTO `color_group` VALUES ('Winterberry Red Metallic', 'Ebony', 73);
INSERT INTO `color_group` VALUES ('Wolf Gray', 'Black', 84);
INSERT INTO `color_group` VALUES ('Wr Blue Pearl', 'Black', 115);
INSERT INTO `color_group` VALUES ('Yellow', 'Black', 54);

SET FOREIGN_KEY_CHECKS = 1;
