/*
 Navicat Premium Data Transfer

 Source Server         : localhost
 Source Server Type    : MySQL
 Source Server Version : 80032
 Source Host           : localhost:3306
 Source Schema         : car

 Target Server Type    : MySQL
 Target Server Version : 80032
 File Encoding         : 65001

 Date: 16/07/2023 13:31:55
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for exterior
-- ----------------------------
DROP TABLE IF EXISTS `exterior`;
CREATE TABLE `exterior`  (
  `exteriorColor` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `count` int(0) NULL DEFAULT NULL,
  PRIMARY KEY (`exteriorColor`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb3 COLLATE = utf8mb3_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of exterior
-- ----------------------------
INSERT INTO `exterior` VALUES ('Abyss Blue Pearl', 135);
INSERT INTO `exterior` VALUES ('Aegean Blue Metallic', 102);
INSERT INTO `exterior` VALUES ('Agate Black', 80);
INSERT INTO `exterior` VALUES ('Agate Black Metallic', 333);
INSERT INTO `exterior` VALUES ('Agate Gray Metallic', 59);
INSERT INTO `exterior` VALUES ('Alabaster Silver Metallic', 184);
INSERT INTO `exterior` VALUES ('Alloy Silver Metallic', 202);
INSERT INTO `exterior` VALUES ('Alpine White', 1124);
INSERT INTO `exterior` VALUES ('Anthracite Gray', 64);
INSERT INTO `exterior` VALUES ('Apex Blue Pearl', 110);
INSERT INTO `exterior` VALUES ('Arctic Blue Metallic', 113);
INSERT INTO `exterior` VALUES ('Arctic Gray Metallic', 55);
INSERT INTO `exterior` VALUES ('Arctic White', 165);
INSERT INTO `exterior` VALUES ('Area 51', 72);
INSERT INTO `exterior` VALUES ('Ashen Gray Metallic', 50);
INSERT INTO `exterior` VALUES ('Aspen White', 125);
INSERT INTO `exterior` VALUES ('Atlantis Blue Metallic', 51);
INSERT INTO `exterior` VALUES ('Atomic Silver', 492);
INSERT INTO `exterior` VALUES ('Attitude Black Metallic', 55);
INSERT INTO `exterior` VALUES ('Aurora Black', 182);
INSERT INTO `exterior` VALUES ('Aurora Black Pearl', 106);
INSERT INTO `exterior` VALUES ('Aurora Red Metallic', 54);
INSERT INTO `exterior` VALUES ('Autumn Green Metallic', 96);
INSERT INTO `exterior` VALUES ('Barcelona Red Metallic', 183);
INSERT INTO `exterior` VALUES ('Basque Red Pearl Ii', 94);
INSERT INTO `exterior` VALUES ('Becketts Black', 86);
INSERT INTO `exterior` VALUES ('Beige', 86);
INSERT INTO `exterior` VALUES ('Bellanova White Pearl', 56);
INSERT INTO `exterior` VALUES ('Billet Clearcoat', 197);
INSERT INTO `exterior` VALUES ('Billet Clearcoat Metallic', 87);
INSERT INTO `exterior` VALUES ('Billet Silver Clearcoat Metallic', 54);
INSERT INTO `exterior` VALUES ('Billet Silver Metallic', 60);
INSERT INTO `exterior` VALUES ('Billet Silver Metallic Clearcoat', 1326);
INSERT INTO `exterior` VALUES ('Black', 12469);
INSERT INTO `exterior` VALUES ('Black Cherry', 99);
INSERT INTO `exterior` VALUES ('Black Cherry Metallic', 55);
INSERT INTO `exterior` VALUES ('Black Clearcoat', 917);
INSERT INTO `exterior` VALUES ('Black Diamond', 111);
INSERT INTO `exterior` VALUES ('Black Granite Metallic', 91);
INSERT INTO `exterior` VALUES ('Black Metallic', 94);
INSERT INTO `exterior` VALUES ('Black Noir Pearl', 224);
INSERT INTO `exterior` VALUES ('Black Obsidian', 683);
INSERT INTO `exterior` VALUES ('Black Onyx', 110);
INSERT INTO `exterior` VALUES ('Black Raven', 726);
INSERT INTO `exterior` VALUES ('Black Sand Pearl', 76);
INSERT INTO `exterior` VALUES ('Black Sapphire Metallic', 1059);
INSERT INTO `exterior` VALUES ('Black Stone', 110);
INSERT INTO `exterior` VALUES ('Black Velvet', 87);
INSERT INTO `exterior` VALUES ('Blizzard Pearl', 337);
INSERT INTO `exterior` VALUES ('Blue', 3072);
INSERT INTO `exterior` VALUES ('Blue Diamond', 55);
INSERT INTO `exterior` VALUES ('Blue Jeans Metallic', 71);
INSERT INTO `exterior` VALUES ('Blue Metallic', 133);
INSERT INTO `exterior` VALUES ('Blue Reflex Mica', 56);
INSERT INTO `exterior` VALUES ('Blue Streak Pearlcoat', 86);
INSERT INTO `exterior` VALUES ('Blue Velvet Metallic', 76);
INSERT INTO `exterior` VALUES ('Blueprint', 86);
INSERT INTO `exterior` VALUES ('Bluestone Metallic', 57);
INSERT INTO `exterior` VALUES ('Bright Silver', 141);
INSERT INTO `exterior` VALUES ('Bright Silver Clearcoat Metallic', 258);
INSERT INTO `exterior` VALUES ('Bright Silver Metallic', 185);
INSERT INTO `exterior` VALUES ('Bright White', 393);
INSERT INTO `exterior` VALUES ('Bright White Clearcoat', 4102);
INSERT INTO `exterior` VALUES ('Brilliant Black', 384);
INSERT INTO `exterior` VALUES ('Brilliant Black Crystal Pearlcoat', 1137);
INSERT INTO `exterior` VALUES ('Brilliant Blue Metallic', 73);
INSERT INTO `exterior` VALUES ('Brilliant Silver', 472);
INSERT INTO `exterior` VALUES ('Brilliant Silver Metallic', 437);
INSERT INTO `exterior` VALUES ('Bronze Alloy Metallic', 56);
INSERT INTO `exterior` VALUES ('Brown', 426);
INSERT INTO `exterior` VALUES ('Burgundy', 380);
INSERT INTO `exterior` VALUES ('Burgundy Velvet Metallic Tinted Clearcoat', 84);
INSERT INTO `exterior` VALUES ('Byron Blue', 99);
INSERT INTO `exterior` VALUES ('Cajun Red Tintcoat', 118);
INSERT INTO `exterior` VALUES ('Calypso Red', 167);
INSERT INTO `exterior` VALUES ('Candy White', 57);
INSERT INTO `exterior` VALUES ('Carbide Gray Metallic', 85);
INSERT INTO `exterior` VALUES ('Carbon Black Metallic', 390);
INSERT INTO `exterior` VALUES ('Carbonized Gray Metallic', 131);
INSERT INTO `exterior` VALUES ('Cardinal Red', 75);
INSERT INTO `exterior` VALUES ('Cardinal Red Metallic', 72);
INSERT INTO `exterior` VALUES ('Carpathian Grey', 203);
INSERT INTO `exterior` VALUES ('Carrara White', 94);
INSERT INTO `exterior` VALUES ('Carrara White Metallic', 125);
INSERT INTO `exterior` VALUES ('Caspian Blue', 89);
INSERT INTO `exterior` VALUES ('Caviar', 372);
INSERT INTO `exterior` VALUES ('Cayenne Red', 167);
INSERT INTO `exterior` VALUES ('Cayenne Red Tintcoat', 64);
INSERT INTO `exterior` VALUES ('Celestial Silver Metallic', 227);
INSERT INTO `exterior` VALUES ('Century White', 55);
INSERT INTO `exterior` VALUES ('Ceramic Gray Clearcoat', 199);
INSERT INTO `exterior` VALUES ('Ceramic White', 194);
INSERT INTO `exterior` VALUES ('Chalk', 76);
INSERT INTO `exterior` VALUES ('Chalk White', 52);
INSERT INTO `exterior` VALUES ('Champagne Silver', 139);
INSERT INTO `exterior` VALUES ('Charcoal', 161);
INSERT INTO `exterior` VALUES ('Cherry Red Tintcoat', 94);
INSERT INTO `exterior` VALUES ('Chili Red Metallic', 88);
INSERT INTO `exterior` VALUES ('Chronos Gray Metallic', 100);
INSERT INTO `exterior` VALUES ('Cinnabar Metallic', 199);
INSERT INTO `exterior` VALUES ('Classic Silver Metallic', 321);
INSERT INTO `exterior` VALUES ('Clear White', 234);
INSERT INTO `exterior` VALUES ('Cloud White', 94);
INSERT INTO `exterior` VALUES ('Cloudburst Gray', 76);
INSERT INTO `exterior` VALUES ('Coliseum Gray', 63);
INSERT INTO `exterior` VALUES ('Corris Grey', 200);
INSERT INTO `exterior` VALUES ('Cosmic Blue Metallic', 59);
INSERT INTO `exterior` VALUES ('Crimson Red Pearl', 174);
INSERT INTO `exterior` VALUES ('Crimson Red Tintcoat', 150);
INSERT INTO `exterior` VALUES ('Crystal Black Pearl', 1032);
INSERT INTO `exterior` VALUES ('Crystal Black Silica', 792);
INSERT INTO `exterior` VALUES ('Crystal Red Tintcoat', 178);
INSERT INTO `exterior` VALUES ('Crystal White', 152);
INSERT INTO `exterior` VALUES ('Crystal White Metallic', 236);
INSERT INTO `exterior` VALUES ('Crystal White Pearl', 1076);
INSERT INTO `exterior` VALUES ('Crystal White Pearl Metallic', 76);
INSERT INTO `exterior` VALUES ('Crystal White Tri-Coat', 773);
INSERT INTO `exterior` VALUES ('Crystal White Tricoat', 102);
INSERT INTO `exterior` VALUES ('Cyber Gray Metallic', 67);
INSERT INTO `exterior` VALUES ('Dark Ash Metallic', 55);
INSERT INTO `exterior` VALUES ('Dark Blue', 67);
INSERT INTO `exterior` VALUES ('Dark Granite Metallic', 78);
INSERT INTO `exterior` VALUES ('Dark Graphite', 68);
INSERT INTO `exterior` VALUES ('Dark Graphite Metallic', 199);
INSERT INTO `exterior` VALUES ('Dark Gray Metallic', 309);
INSERT INTO `exterior` VALUES ('Dark Moon Blue Metallic', 169);
INSERT INTO `exterior` VALUES ('Dark Moss', 63);
INSERT INTO `exterior` VALUES ('Dark Sapphire Blue Metallic', 76);
INSERT INTO `exterior` VALUES ('Dark Sky Metallic', 102);
INSERT INTO `exterior` VALUES ('Dark Slate Metallic', 145);
INSERT INTO `exterior` VALUES ('Daytona Gray Pearl Effect', 342);
INSERT INTO `exterior` VALUES ('Dazzling White', 91);
INSERT INTO `exterior` VALUES ('Db Black Clearcoat', 130);
INSERT INTO `exterior` VALUES ('Db Black Crystal Clearcoat', 173);
INSERT INTO `exterior` VALUES ('Deep', 52);
INSERT INTO `exterior` VALUES ('Deep Black Pearl', 74);
INSERT INTO `exterior` VALUES ('Deep Black Pearl Effect', 792);
INSERT INTO `exterior` VALUES ('Deep Blue Pearl', 125);
INSERT INTO `exterior` VALUES ('Deep Cherry Red Crystal Pearlcoat', 215);
INSERT INTO `exterior` VALUES ('Deep Crystal Blue Mica', 480);
INSERT INTO `exterior` VALUES ('Deep Scarlet Pearl', 53);
INSERT INTO `exterior` VALUES ('Deep Sea Blue', 53);
INSERT INTO `exterior` VALUES ('Delmonico Red Pearlcoat', 351);
INSERT INTO `exterior` VALUES ('Denim Blue', 99);
INSERT INTO `exterior` VALUES ('Denim Blue Metallic', 183);
INSERT INTO `exterior` VALUES ('Designo Cardinal Red Metallic', 55);
INSERT INTO `exterior` VALUES ('Designo Diamond White', 62);
INSERT INTO `exterior` VALUES ('Designo Diamond White Metallic', 122);
INSERT INTO `exterior` VALUES ('Destroyer Gray Clearcoat', 181);
INSERT INTO `exterior` VALUES ('Diamond', 50);
INSERT INTO `exterior` VALUES ('Diamond Black', 1242);
INSERT INTO `exterior` VALUES ('Diamond Black Crystal Pearlcoat', 133);
INSERT INTO `exterior` VALUES ('Diamond Red', 116);
INSERT INTO `exterior` VALUES ('Diamond White', 85);
INSERT INTO `exterior` VALUES ('Diamond White Pearl', 52);
INSERT INTO `exterior` VALUES ('Dolomite Silver Metallic', 66);
INSERT INTO `exterior` VALUES ('Dynamic Sunstone Red', 70);
INSERT INTO `exterior` VALUES ('Ebony Black', 423);
INSERT INTO `exterior` VALUES ('Ebony Twilight Metallic', 1157);
INSERT INTO `exterior` VALUES ('Eiger Grey', 202);
INSERT INTO `exterior` VALUES ('Eminent White Pearl', 469);
INSERT INTO `exterior` VALUES ('Eternal Blue Mica', 123);
INSERT INTO `exterior` VALUES ('Everlasting Silver', 128);
INSERT INTO `exterior` VALUES ('F8 Green', 152);
INSERT INTO `exterior` VALUES ('Fathom Blue Pearl', 68);
INSERT INTO `exterior` VALUES ('Fathom Blue Pearlcoat', 99);
INSERT INTO `exterior` VALUES ('Firecracker Red Clearcoat', 158);
INSERT INTO `exterior` VALUES ('Firenze Red', 162);
INSERT INTO `exterior` VALUES ('Flame Red Clearcoat', 249);
INSERT INTO `exterior` VALUES ('Flight Blue', 91);
INSERT INTO `exterior` VALUES ('Florett Silver Metallic', 406);
INSERT INTO `exterior` VALUES ('Fresh Powder', 100);
INSERT INTO `exterior` VALUES ('Frost White Pearl', 125);
INSERT INTO `exterior` VALUES ('Frostbite', 151);
INSERT INTO `exterior` VALUES ('Frozen White', 63);
INSERT INTO `exterior` VALUES ('Fuji White', 1135);
INSERT INTO `exterior` VALUES ('Galactic Gray', 60);
INSERT INTO `exterior` VALUES ('Glacial White Pearl', 170);
INSERT INTO `exterior` VALUES ('Glacier Silver Metallic', 277);
INSERT INTO `exterior` VALUES ('Glacier White', 467);
INSERT INTO `exterior` VALUES ('Glacier White Metallic', 783);
INSERT INTO `exterior` VALUES ('Gloss Black', 194);
INSERT INTO `exterior` VALUES ('Go Mango!', 131);
INSERT INTO `exterior` VALUES ('Gold', 202);
INSERT INTO `exterior` VALUES ('Granite Clearcoat', 59);
INSERT INTO `exterior` VALUES ('Granite Clearcoat Metallic', 70);
INSERT INTO `exterior` VALUES ('Granite Crystal', 58);
INSERT INTO `exterior` VALUES ('Granite Crystal Clearcoat Metallic', 2043);
INSERT INTO `exterior` VALUES ('Granite Crystal Metallic', 53);
INSERT INTO `exterior` VALUES ('Granite Crystal Metallic Clearcoat', 201);
INSERT INTO `exterior` VALUES ('Granite Pearlcoat', 258);
INSERT INTO `exterior` VALUES ('Graphite Blue', 61);
INSERT INTO `exterior` VALUES ('Graphite Gray', 58);
INSERT INTO `exterior` VALUES ('Graphite Gray Metallic', 233);
INSERT INTO `exterior` VALUES ('Graphite Luster Metallic', 68);
INSERT INTO `exterior` VALUES ('Graphite Metallic', 114);
INSERT INTO `exterior` VALUES ('Graphite Shadow', 603);
INSERT INTO `exterior` VALUES ('Gravity Gray', 229);
INSERT INTO `exterior` VALUES ('Gray', 6323);
INSERT INTO `exterior` VALUES ('Gray Metallic', 346);
INSERT INTO `exterior` VALUES ('Green', 360);
INSERT INTO `exterior` VALUES ('Gt Silver Metallic', 72);
INSERT INTO `exterior` VALUES ('Gun Metallic', 1189);
INSERT INTO `exterior` VALUES ('Gunmetal Metallic', 91);
INSERT INTO `exterior` VALUES ('Hakuba Silver', 69);
INSERT INTO `exterior` VALUES ('Hampton Gray', 106);
INSERT INTO `exterior` VALUES ('Harbor Gray Metallic', 62);
INSERT INTO `exterior` VALUES ('Hellraisin', 52);
INSERT INTO `exterior` VALUES ('Hermosa Blue', 381);
INSERT INTO `exterior` VALUES ('Horizon Blue', 50);
INSERT INTO `exterior` VALUES ('Horizon Blue Pearl', 55);
INSERT INTO `exterior` VALUES ('Hydro Blue Pearlcoat', 107);
INSERT INTO `exterior` VALUES ('Hyper White', 104);
INSERT INTO `exterior` VALUES ('Ibis White', 452);
INSERT INTO `exterior` VALUES ('Ice', 50);
INSERT INTO `exterior` VALUES ('Ice Silver Metallic', 1015);
INSERT INTO `exterior` VALUES ('Ice White', 138);
INSERT INTO `exterior` VALUES ('Iconic Silver Metallic', 158);
INSERT INTO `exterior` VALUES ('Imperial Blue Metallic', 119);
INSERT INTO `exterior` VALUES ('Indigo Blue', 92);
INSERT INTO `exterior` VALUES ('Indus Silver', 172);
INSERT INTO `exterior` VALUES ('Inferno Red', 61);
INSERT INTO `exterior` VALUES ('Infinite Black Metallic', 343);
INSERT INTO `exterior` VALUES ('Ingot Silver', 159);
INSERT INTO `exterior` VALUES ('Ingot Silver Metallic', 381);
INSERT INTO `exterior` VALUES ('Intense Blue', 104);
INSERT INTO `exterior` VALUES ('Iridescent Pearl Tricoat', 204);
INSERT INTO `exterior` VALUES ('Iridium', 95);
INSERT INTO `exterior` VALUES ('Iridium Metallic', 194);
INSERT INTO `exterior` VALUES ('Iridium Silver Metallic', 238);
INSERT INTO `exterior` VALUES ('Ivory White', 85);
INSERT INTO `exterior` VALUES ('Jasmine Green Metallic', 59);
INSERT INTO `exterior` VALUES ('Java Metallic', 51);
INSERT INTO `exterior` VALUES ('Jazz Blue Pearlcoat', 81);
INSERT INTO `exterior` VALUES ('Jet Black', 596);
INSERT INTO `exterior` VALUES ('Jet Black Metallic', 130);
INSERT INTO `exterior` VALUES ('Jet Black Mica', 900);
INSERT INTO `exterior` VALUES ('Labrador Black Metallic', 74);
INSERT INTO `exterior` VALUES ('Labrador Black Pearl', 110);
INSERT INTO `exterior` VALUES ('Lakeside Blue', 118);
INSERT INTO `exterior` VALUES ('Lapis Blue Pearl', 65);
INSERT INTO `exterior` VALUES ('Liquid Carbon Metallic', 141);
INSERT INTO `exterior` VALUES ('Liquid Platinum', 321);
INSERT INTO `exterior` VALUES ('Liquid Silver Metallic', 91);
INSERT INTO `exterior` VALUES ('Loire Blue', 70);
INSERT INTO `exterior` VALUES ('Lunar Blue Metallic', 165);
INSERT INTO `exterior` VALUES ('Lunar Silver Metallic', 674);
INSERT INTO `exterior` VALUES ('Lunar White', 75);
INSERT INTO `exterior` VALUES ('Luxury White Pearlcoat', 54);
INSERT INTO `exterior` VALUES ('Machine Gray', 147);
INSERT INTO `exterior` VALUES ('Machine Gray Metallic', 631);
INSERT INTO `exterior` VALUES ('Magnetic', 144);
INSERT INTO `exterior` VALUES ('Magnetic Black', 408);
INSERT INTO `exterior` VALUES ('Magnetic Gray', 135);
INSERT INTO `exterior` VALUES ('Magnetic Gray Metallic', 649);
INSERT INTO `exterior` VALUES ('Magnetic Metallic', 273);
INSERT INTO `exterior` VALUES ('Magnetite Gray Metallic', 555);
INSERT INTO `exterior` VALUES ('Majestic Black Pearl', 380);
INSERT INTO `exterior` VALUES ('Majestic White', 514);
INSERT INTO `exterior` VALUES ('Manhattan Gray Metallic', 170);
INSERT INTO `exterior` VALUES ('Manhattan Noir Metallic', 62);
INSERT INTO `exterior` VALUES ('Maroon', 260);
INSERT INTO `exterior` VALUES ('Matador Red Mica', 145);
INSERT INTO `exterior` VALUES ('Maximum Steel Metallic', 337);
INSERT INTO `exterior` VALUES ('Melbourne Red Metallic', 78);
INSERT INTO `exterior` VALUES ('Mercury Gray Metallic', 177);
INSERT INTO `exterior` VALUES ('Metal', 82);
INSERT INTO `exterior` VALUES ('Metallic', 304);
INSERT INTO `exterior` VALUES ('Meteor Gray Mica', 93);
INSERT INTO `exterior` VALUES ('Midnight Black', 335);
INSERT INTO `exterior` VALUES ('Midnight Black Metallic', 523);
INSERT INTO `exterior` VALUES ('Midnight Blue Metallic', 94);
INSERT INTO `exterior` VALUES ('Mineral Black', 115);
INSERT INTO `exterior` VALUES ('Mineral Gray', 84);
INSERT INTO `exterior` VALUES ('Mineral Gray Metallic', 361);
INSERT INTO `exterior` VALUES ('Mineral Silver', 57);
INSERT INTO `exterior` VALUES ('Mineral White Metallic', 405);
INSERT INTO `exterior` VALUES ('Mocha', 75);
INSERT INTO `exterior` VALUES ('Mocha Almond', 54);
INSERT INTO `exterior` VALUES ('Mocha Steel Metallic', 53);
INSERT INTO `exterior` VALUES ('Modern Steel Metallic', 902);
INSERT INTO `exterior` VALUES ('Mojave Silver Metallic', 67);
INSERT INTO `exterior` VALUES ('Molten Silver', 116);
INSERT INTO `exterior` VALUES ('Monaco White', 70);
INSERT INTO `exterior` VALUES ('Monsoon Gray Metallic', 145);
INSERT INTO `exterior` VALUES ('Moonlight Blue Metallic', 191);
INSERT INTO `exterior` VALUES ('Moonlight White', 163);
INSERT INTO `exterior` VALUES ('Moonstone Gray Metallic', 151);
INSERT INTO `exterior` VALUES ('Moonstone White', 191);
INSERT INTO `exterior` VALUES ('Mosaic Black Metallic', 284);
INSERT INTO `exterior` VALUES ('Mythos Black Metallic', 719);
INSERT INTO `exterior` VALUES ('Narvik Black', 282);
INSERT INTO `exterior` VALUES ('Nautical Blue Metallic', 65);
INSERT INTO `exterior` VALUES ('Navarra Blue Metallic', 252);
INSERT INTO `exterior` VALUES ('Nebula Gray Pearl', 403);
INSERT INTO `exterior` VALUES ('Night Black', 60);
INSERT INTO `exterior` VALUES ('Night Blue Metallic', 132);
INSERT INTO `exterior` VALUES ('Nightfall Gray Metallic', 95);
INSERT INTO `exterior` VALUES ('Nightfall Mica', 112);
INSERT INTO `exterior` VALUES ('Northsky Blue Metallic', 73);
INSERT INTO `exterior` VALUES ('Obsidian Black', 339);
INSERT INTO `exterior` VALUES ('Obsidian Black Metallic', 215);
INSERT INTO `exterior` VALUES ('Obsidian Blue Pearl', 145);
INSERT INTO `exterior` VALUES ('Ocean Blue Metallic', 53);
INSERT INTO `exterior` VALUES ('Octane Red Pearlcoat', 335);
INSERT INTO `exterior` VALUES ('Onyx Black', 1302);
INSERT INTO `exterior` VALUES ('Onyx Black Metallic', 304);
INSERT INTO `exterior` VALUES ('Opal White Pearl Effect', 80);
INSERT INTO `exterior` VALUES ('Orange', 189);
INSERT INTO `exterior` VALUES ('Orca Black Metallic', 158);
INSERT INTO `exterior` VALUES ('Osmium Gray Metallic', 97);
INSERT INTO `exterior` VALUES ('Oxford White', 993);
INSERT INTO `exterior` VALUES ('Pacific Blue', 141);
INSERT INTO `exterior` VALUES ('Pacific Blue Metallic', 113);
INSERT INTO `exterior` VALUES ('Palladium Silver Metallic', 64);
INSERT INTO `exterior` VALUES ('Passion Red', 72);
INSERT INTO `exterior` VALUES ('Patriot Blue Pearlcoat', 142);
INSERT INTO `exterior` VALUES ('Pearl', 98);
INSERT INTO `exterior` VALUES ('Pearl White', 472);
INSERT INTO `exterior` VALUES ('Pepperdust Metallic', 69);
INSERT INTO `exterior` VALUES ('Performance Red Pearl', 104);
INSERT INTO `exterior` VALUES ('Phantom Black', 405);
INSERT INTO `exterior` VALUES ('Phytonic Blue Metallic', 128);
INSERT INTO `exterior` VALUES ('Pitch Black', 63);
INSERT INTO `exterior` VALUES ('Pitch Black Clearcoat', 667);
INSERT INTO `exterior` VALUES ('Platinum', 65);
INSERT INTO `exterior` VALUES ('Platinum Graphite', 149);
INSERT INTO `exterior` VALUES ('Platinum Gray Metallic', 828);
INSERT INTO `exterior` VALUES ('Platinum White', 64);
INSERT INTO `exterior` VALUES ('Platinum White Pearl', 1140);
INSERT INTO `exterior` VALUES ('Polar White', 835);
INSERT INTO `exterior` VALUES ('Polished Metal Metallic', 110);
INSERT INTO `exterior` VALUES ('Polymetal Gray Metallic', 293);
INSERT INTO `exterior` VALUES ('Portofino Blue', 94);
INSERT INTO `exterior` VALUES ('Portofino Gray', 171);
INSERT INTO `exterior` VALUES ('Predawn Gray Mica', 179);
INSERT INTO `exterior` VALUES ('Pristine White', 359);
INSERT INTO `exterior` VALUES ('Pure Gray', 59);
INSERT INTO `exterior` VALUES ('Pure Red', 55);
INSERT INTO `exterior` VALUES ('Pure White', 1147);
INSERT INTO `exterior` VALUES ('Purple', 61);
INSERT INTO `exterior` VALUES ('Pyrite Silver Metallic', 299);
INSERT INTO `exterior` VALUES ('Quartz Blue Pearl', 117);
INSERT INTO `exterior` VALUES ('Quartz White', 225);
INSERT INTO `exterior` VALUES ('Quartz White Pearl', 229);
INSERT INTO `exterior` VALUES ('Quicksilver Metallic', 844);
INSERT INTO `exterior` VALUES ('Race Red', 149);
INSERT INTO `exterior` VALUES ('Radiant Red', 101);
INSERT INTO `exterior` VALUES ('Radiant Red Metallic', 72);
INSERT INTO `exterior` VALUES ('Radiant Silver Metallic', 380);
INSERT INTO `exterior` VALUES ('Rallye Red', 56);
INSERT INTO `exterior` VALUES ('Rapid Red Metallic Tinted Clearcoat', 91);
INSERT INTO `exterior` VALUES ('Red', 2701);
INSERT INTO `exterior` VALUES ('Red Horizon Tintcoat', 80);
INSERT INTO `exterior` VALUES ('Red Quartz Tintcoat', 193);
INSERT INTO `exterior` VALUES ('Redline 2 Coat Pearl', 150);
INSERT INTO `exterior` VALUES ('Reflex Silver Metallic', 201);
INSERT INTO `exterior` VALUES ('Rhino Clearcoat', 72);
INSERT INTO `exterior` VALUES ('Rhodium Silver', 62);
INSERT INTO `exterior` VALUES ('Ruby Flare Pearl', 95);
INSERT INTO `exterior` VALUES ('Ruby Red', 61);
INSERT INTO `exterior` VALUES ('Ruby Red Metallic Tinted Clearcoat', 228);
INSERT INTO `exterior` VALUES ('Samurai Gray Metallic', 102);
INSERT INTO `exterior` VALUES ('Sangria Red', 88);
INSERT INTO `exterior` VALUES ('Santorini Black', 1026);
INSERT INTO `exterior` VALUES ('Santorini Black Metallic', 90);
INSERT INTO `exterior` VALUES ('Sapphire Blue', 105);
INSERT INTO `exterior` VALUES ('Sarge Green Clearcoat', 59);
INSERT INTO `exterior` VALUES ('Satin Cashmere Metallic', 52);
INSERT INTO `exterior` VALUES ('Satin Steel Gray Metallic', 65);
INSERT INTO `exterior` VALUES ('Satin Steel Metallic', 908);
INSERT INTO `exterior` VALUES ('Satin White Pearl', 110);
INSERT INTO `exterior` VALUES ('Scarlet Ember', 155);
INSERT INTO `exterior` VALUES ('Scarlet Red', 120);
INSERT INTO `exterior` VALUES ('Scarlet Red Pearl', 87);
INSERT INTO `exterior` VALUES ('Selenite Gray Metallic', 115);
INSERT INTO `exterior` VALUES ('Shadow Black', 566);
INSERT INTO `exterior` VALUES ('Shadow Gray Metallic', 138);
INSERT INTO `exterior` VALUES ('Shadow Metallic', 139);
INSERT INTO `exterior` VALUES ('Shale Gray Metallic', 104);
INSERT INTO `exterior` VALUES ('Shimmering Silver', 75);
INSERT INTO `exterior` VALUES ('Shimmering Silver Pearl', 90);
INSERT INTO `exterior` VALUES ('Silicon Silver', 68);
INSERT INTO `exterior` VALUES ('Silk Blue Metallic', 169);
INSERT INTO `exterior` VALUES ('Silky Silver', 161);
INSERT INTO `exterior` VALUES ('Silver', 4382);
INSERT INTO `exterior` VALUES ('Silver Coast Metallic', 62);
INSERT INTO `exterior` VALUES ('Silver Ice Metallic', 691);
INSERT INTO `exterior` VALUES ('Silver Lining Metallic', 188);
INSERT INTO `exterior` VALUES ('Silver Metallic', 147);
INSERT INTO `exterior` VALUES ('Silver Mist Clearcoat', 169);
INSERT INTO `exterior` VALUES ('Silver Radiance Metallic', 58);
INSERT INTO `exterior` VALUES ('Silver Sky Metallic', 245);
INSERT INTO `exterior` VALUES ('Silver Zynith', 110);
INSERT INTO `exterior` VALUES ('Sinamon Stick', 54);
INSERT INTO `exterior` VALUES ('Siren Red Tintcoat', 57);
INSERT INTO `exterior` VALUES ('Slate Gray', 79);
INSERT INTO `exterior` VALUES ('Smoke Show', 83);
INSERT INTO `exterior` VALUES ('Smokey Quartz Metallic', 57);
INSERT INTO `exterior` VALUES ('Snow White Pearl', 647);
INSERT INTO `exterior` VALUES ('Snowflake White Pearl', 399);
INSERT INTO `exterior` VALUES ('Snowflake White Pearl Metallic', 54);
INSERT INTO `exterior` VALUES ('Snowflake White Pearl Mica', 222);
INSERT INTO `exterior` VALUES ('Sonic Gray Pearl', 154);
INSERT INTO `exterior` VALUES ('Sonic Silver Metallic', 321);
INSERT INTO `exterior` VALUES ('Soul Red Crystal Metallic', 473);
INSERT INTO `exterior` VALUES ('Soul Red Metallic', 128);
INSERT INTO `exterior` VALUES ('Space Gray Metallic', 96);
INSERT INTO `exterior` VALUES ('Sparkling Silver', 236);
INSERT INTO `exterior` VALUES ('Star White', 145);
INSERT INTO `exterior` VALUES ('Starfire Pearl', 165);
INSERT INTO `exterior` VALUES ('Steel / Graphite', 75);
INSERT INTO `exterior` VALUES ('Steel Gray', 132);
INSERT INTO `exterior` VALUES ('Steel Gray Metallic', 90);
INSERT INTO `exterior` VALUES ('Stellar Black Metallic', 486);
INSERT INTO `exterior` VALUES ('Stellar Silver', 53);
INSERT INTO `exterior` VALUES ('Sterling Gray Metallic', 142);
INSERT INTO `exterior` VALUES ('Still Night Pearl', 79);
INSERT INTO `exterior` VALUES ('Sting Gray Clearcoat', 169);
INSERT INTO `exterior` VALUES ('Stone Blue Metallic', 56);
INSERT INTO `exterior` VALUES ('Storm Blue', 71);
INSERT INTO `exterior` VALUES ('Stormy Sea', 137);
INSERT INTO `exterior` VALUES ('Summit White', 3796);
INSERT INTO `exterior` VALUES ('Super Black', 510);
INSERT INTO `exterior` VALUES ('Super White', 544);
INSERT INTO `exterior` VALUES ('Symphony Silver', 180);
INSERT INTO `exterior` VALUES ('Taffeta White', 91);
INSERT INTO `exterior` VALUES ('Tan', 160);
INSERT INTO `exterior` VALUES ('Tango Red Metallic', 72);
INSERT INTO `exterior` VALUES ('Thunder Gray', 113);
INSERT INTO `exterior` VALUES ('Thunder Gray Metallic', 76);
INSERT INTO `exterior` VALUES ('Titanium Flash Mica', 52);
INSERT INTO `exterior` VALUES ('Titanium Gray', 96);
INSERT INTO `exterior` VALUES ('Titanium Rush Metallic', 88);
INSERT INTO `exterior` VALUES ('Titanium Silver', 109);
INSERT INTO `exterior` VALUES ('Tornado Red', 103);
INSERT INTO `exterior` VALUES ('Torred Clearcoat', 152);
INSERT INTO `exterior` VALUES ('Tourmaline Blue Metallic', 148);
INSERT INTO `exterior` VALUES ('Triple Nickel Clearcoat', 146);
INSERT INTO `exterior` VALUES ('True Blue Pearlcoat', 167);
INSERT INTO `exterior` VALUES ('Tungsten Metallic', 226);
INSERT INTO `exterior` VALUES ('Tuxedo Black', 66);
INSERT INTO `exterior` VALUES ('Tuxedo Black Metallic', 227);
INSERT INTO `exterior` VALUES ('Twilight Black', 181);
INSERT INTO `exterior` VALUES ('Twilight Blue Metallic', 127);
INSERT INTO `exterior` VALUES ('Ultimate Black', 63);
INSERT INTO `exterior` VALUES ('Ultra Black', 128);
INSERT INTO `exterior` VALUES ('Ultra White', 321);
INSERT INTO `exterior` VALUES ('Velvet Red Pearlcoat', 654);
INSERT INTO `exterior` VALUES ('Venetian Red', 83);
INSERT INTO `exterior` VALUES ('Venetian Red Pearl', 205);
INSERT INTO `exterior` VALUES ('Vice White', 101);
INSERT INTO `exterior` VALUES ('Victory Red', 62);
INSERT INTO `exterior` VALUES ('Volcano Grey Metallic', 94);
INSERT INTO `exterior` VALUES ('White', 9909);
INSERT INTO `exterior` VALUES ('White Clearcoat', 64);
INSERT INTO `exterior` VALUES ('White Diamond', 143);
INSERT INTO `exterior` VALUES ('White Diamond Pearl', 365);
INSERT INTO `exterior` VALUES ('White Diamond Tri-Coat', 207);
INSERT INTO `exterior` VALUES ('White Frost Tri-Coat', 691);
INSERT INTO `exterior` VALUES ('White Frost Tricoat', 116);
INSERT INTO `exterior` VALUES ('White Knuckle', 68);
INSERT INTO `exterior` VALUES ('White Knuckle Clearcoat', 699);
INSERT INTO `exterior` VALUES ('White Metallic', 115);
INSERT INTO `exterior` VALUES ('White Orchid Pearl', 139);
INSERT INTO `exterior` VALUES ('White Pearl', 71);
INSERT INTO `exterior` VALUES ('White Platinum', 154);
INSERT INTO `exterior` VALUES ('White Platinum Metallic Tri-Coat', 51);
INSERT INTO `exterior` VALUES ('White Platinum Tri-Coat Metallic', 358);
INSERT INTO `exterior` VALUES ('White Silver Metallic', 58);
INSERT INTO `exterior` VALUES ('Wind Chill Pearl', 129);
INSERT INTO `exterior` VALUES ('Winterberry Red Metallic', 96);
INSERT INTO `exterior` VALUES ('Wolf Gray', 92);
INSERT INTO `exterior` VALUES ('Wr Blue Pearl', 138);
INSERT INTO `exterior` VALUES ('Yellow', 86);
INSERT INTO `exterior` VALUES ('Yulong White', 113);

SET FOREIGN_KEY_CHECKS = 1;
